### ISSUE TITLE
Not Downloading

### ISSUE THREAD

**Issue by BoyCanad** [bunnykek/Apple-Music-Animated-Artwork-Fetcher#11]
Hello I'm new, i don't know this stuff but i'm getting this error

Traceback (most recent call last):
  File "C:\Users\Admin\Apple-Music-Animated-Artwork-Fetcher\fetcher.py", line 325, in <module>
    fetch.album(id_, country, artwork_type, rep, aud)
  File "C:\Users\Admin\Apple-Music-Animated-Artwork-Fetcher\fetcher.py", line 68, in album
    self.processVideo(m3u8_, rep)
  File "C:\Users\Admin\Apple-Music-Animated-Artwork-Fetcher\fetcher.py", line 167, in processVideo
    subprocess.Popen(['ffmpeg', '-loglevel', 'quiet',
  File "D:\Program Files\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\Program Files\Python311\Lib\subprocess.py", line 1493, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by bunnykek** [comment]
The script is working fine. There some issue in your system. Better reinstall the python to its default location.

**Comment by jasontkenny** [comment]
Having the same issue
