### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by jasontkenny** [bunnykek/Apple-Music-Animated-Artwork-Fetcher#13]
Downloading the video...
Traceback (most recent call last):
  File "C:\Users\jason\Apple-Music-Animated-Artwork-Fetcher\fetcher.py", line 325, in <module>
    fetch.album(id_, country, artwork_type, rep, aud)
  File "C:\Users\jason\Apple-Music-Animated-Artwork-Fetcher\fetcher.py", line 68, in album
    self.processVideo(m3u8_, rep)
  File "C:\Users\jason\Apple-Music-Animated-Artwork-Fetcher\fetcher.py", line 167, in processVideo
    subprocess.Popen(['ffmpeg', '-loglevel', 'quiet',
  File "C:\Users\jason\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\jason\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by bunnykek** [comment]
https://github.com/bunnykek/Apple-Music-Animated-Artwork-Fetcher/issues/12#issuecomment-1668241629
