### ISSUE TITLE
failing after music is downloaded

### ISSUE THREAD

**Issue by TeslaMan3092** [bunnykek/Apple-Music-Animated-Artwork-Fetcher#15]
Not sure what to do here but i had an issue before with ffmpeg, i fixed it by putting the executable in /usr/bin
on fedora linux with KDE desktop
```
[kason@fedora Apple-Music-Animated-Artwork-Fetcher]$ python3 fetcher.py -T tall -L 2 -A https://music.apple.com/us/album/planet-her-deluxe/1574004234

             /$$$$$$$$          /$$               /$$                          
            | $$_____/         | $$              | $$                          
            | $$     /$$$$$$  /$$$$$$    /$$$$$$$| $$$$$$$   /$$$$$$   /$$$$$$ 
            | $$$$$ /$$__  $$|_  $$_/   /$$_____/| $$__  $$ /$$__  $$ /$$__  $$
            | $$__/| $$$$$$$$  | $$    | $$      | $$  \ $$| $$$$$$$$| $$  \__/
            | $$   | $$_____/  | $$ /$$| $$      | $$  | $$| $$_____/| $$      
            | $$   |  $$$$$$$  |  $$$$/|  $$$$$$$| $$  | $$|  $$$$$$$| $$      
            |__/    \_______/   \___/   \_______/|__/  |__/ \_______/|__/      
                    Apple-Music animated cover artwork downloader                      
                                                                -- by bunny  
    
Checking if the static token is still alive...
Token expired!
Updating the token...
Token updated!
+----+------------+------------+-------+------+
| ID | Resolution |  Bitrate   | Codec | FPS  |
+----+------------+------------+-------+------+
| 1  |  664x886   | 1.98 Mb/s  |  hvc1 | 24.0 |
| 2  |  310x414   |  0.3 Mb/s  |  avc1 | 24.0 |
| 3  |  352x470   | 0.43 Mb/s  |  avc1 | 24.0 |
| 4  |  394x526   | 0.62 Mb/s  |  avc1 | 24.0 |
| 5  |  436x582   | 0.95 Mb/s  |  avc1 | 24.0 |
| 7  |  486x648   | 1.91 Mb/s  |  avc1 | 24.0 |
| 8  |  830x1106  | 3.53 Mb/s  |  avc1 | 24.0 |
| 9  |  830x1108  | 4.62 Mb/s  |  avc1 | 24.0 |
| 12 | 1078x1438  |  8.0 Mb/s  |  avc1 | 24.0 |
| 13 |  310x414   | 0.31 Mb/s  |  hvc1 | 24.0 |
| 14 |  394x526   | 0.53 Mb/s  |  hvc1 | 24.0 |
| 15 |  436x582   | 0.77 Mb/s  |  hvc1 | 24.0 |
| 17 |  486x648   | 1.47 Mb/s  |  hvc1 | 24.0 |
| 18 |  830x1106  | 2.77 Mb/s  |  hvc1 | 24.0 |
| 19 |  830x1108  | 3.64 Mb/s  |  hvc1 | 24.0 |
| 22 | 1078x1438  | 6.05 Mb/s  |  hvc1 | 24.0 |
| 23 | 1080x1440  | 8.56 Mb/s  |  hvc1 | 24.0 |
| 24 | 1662x2216  | 14.39 Mb/s |  hvc1 | 24.0 |
| 27 | 2048x2732  | 23.29 Mb/s |  hvc1 | 24.0 |
+----+------------+------------+-------+------+
Enter the ID: 4

Downloading the video...
Video downloaded.

Audio tracks:
+-----------+----------------------------------------+
| Track No. | Name                                   |
+-----------+----------------------------------------+
|     1     | Woman                                  |
|     2     | Naked                                  |
|     3     | Payday (feat. Young Thug)              |
|     4     | Get Into It (Yuh)                      |
|     5     | Need To Know                           |
|     6     | I Don't Do Drugs (feat. Ariana Grande) |
|     7     | Love To Dream                          |
|     8     | You Right                              |
|     9     | Been Like This                         |
|     10    | Options (feat. JID)                    |
|     11    | Ain't Shit                             |
|     12    | Imagine                                |
|     13    | Alone                                  |
|     14    | Kiss Me More (feat. SZA)               |
|     15    | You Right (Extended)                   |
|     16    | Up And Down                            |
|     17    | Tonight (feat. Eve)                    |
|     18    | Ride                                   |
|     19    | Why Why (feat. Gunna)                  |
+-----------+----------------------------------------+

Select the audio track number : 14

Downloading the audio...
Audio downloaded.

Multiplexing...
Done.
Traceback (most recent call last):
  File "/home/kason/Apple-Music-Animated-Artwork-Fetcher/fetcher.py", line 325, in <module>
    fetch.album(id_, country, artwork_type, rep, aud)
  File "/home/kason/Apple-Music-Animated-Artwork-Fetcher/fetcher.py", line 72, in album
    os.remove("fixed.mp4")
FileNotFoundError: [Errno 2] No such file or directory: 'fixed.mp4'
[kason@fedora Apple-Music-Animated-Artwork-Fetcher]$
```

**Comment by bunnykek** [comment]
The final artwork has been downloaded. The error has occured when deleting the temporary files. This error never happened before. Anyways, i will do changes in the code which might me causing this issue. Currently I have exams so wait for 3-4 days.

**Comment by bunnykek** [comment]
Updated. do git pull and try again.
