### ISSUE TITLE
Error regenerating token

### ISSUE THREAD

**Issue by down-bad** [bunnykek/Apple-Music-Animated-Artwork-Fetcher#6]
Checking if the static token is still alive...
Regenerating a new token.
Traceback (most recent call last):
  File "C:\Users\vasil\Documents\GitHub\Apple-Music-Animated-Artwork-Fetcher\fetcher.py", line 165, in <module>
    token = get_auth_token()
  File "C:\Users\vasil\Documents\GitHub\Apple-Music-Animated-Artwork-Fetcher\fetcher.py", line 42, in get_auth_token
    return re.search(r"(eyJhbGc.+?)%22%7D", response.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by bunnykek** [comment]
You are using the old version of fetcher.
You should update/reinstall it.

**Comment by down-bad** [comment]
You are right, I thought I did but GitHub desktop trolled me. Thanks.
