### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by down-bad** [bunnykek/Apple-Music-Animated-Artwork-Fetcher#8]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vasil\Documents\GitHub\Apple-Music-Animated-Artwork-Fetcher\fetcher.py", line 325, in <module>
    fetch.album(id_, country, artwork_type, rep, aud)
  File "C:\Users\vasil\Documents\GitHub\Apple-Music-Animated-Artwork-Fetcher\fetcher.py", line 51, in album
    album_json = self.get_json(id_, country, 'album')
  File "C:\Users\vasil\Documents\GitHub\Apple-Music-Animated-Artwork-Fetcher\fetcher.py", line 139, in get_json
    return response.json()
  File "C:\Python310\lib\site-packages\requests\models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] : 0

**Comment by bunnykek** [comment]
Fixed it. Reclone it
