### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by jasontkenny** [bunnykek/Apple-Music-Animated-Artwork-Fetcher#9]
Traceback (most recent call last):
  File "C:\Users\jsnkn\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jsnkn\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jsnkn\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jsnkn\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jsnkn\Apple-Music-Animated-Artwork-Fetcher\fetcher.py", line 325, in <module>
    fetch.album(id_, country, artwork_type, rep, aud)
  File "C:\Users\jsnkn\Apple-Music-Animated-Artwork-Fetcher\fetcher.py", line 51, in album
    album_json = self.get_json(id_, country, 'album')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jsnkn\Apple-Music-Animated-Artwork-Fetcher\fetcher.py", line 139, in get_json
    return response.json()
           ^^^^^^^^^^^^^^^
  File "C:\Users\jsnkn\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by bunnykek** [comment]
Fixed. Try now
